### ISSUE TITLE
Akash commands (Implimented)

### ISSUE THREAD

**Issue by reecepbcups** [Reecepbcups/minecraft-panel#9]
Another
https://github.com/itzg/docker-minecraft-server

**Comment by Reecepbcups** [comment]
docker run -d -it -p 25565:25565 --name mc -e EULA=TRUE -e VERSION=1.18.2 itzg/minecraft-server:java15

docker logs -f mc

docker stop mc
docker start mc



docker exec -i mc rcon-cli


docker run -d -it -p 25565:25565 --name mc itzg/minecraft-server

docker attach mc



# Uses TCP socket to attach from another machine
docker -H $HOST:2375 attach mc

# docker -H 127.0.0.1:2375 attach mc2



## https://mctools.readthedocs.io/en/master/client.html
## https://mctools.readthedocs.io/en/master/rcon.html
## (Secrets) https://github.com/itzg/docker-minecraft-server#miscellaneous-options


## For minigames, should we use https://github.com/pufferfish-gg/Pufferfish ? -e TYPE=PUFFERFISH

# do these work? - -e MEMORY=4G -e USE_AIKAR_FLAGS=true
-e ENABLE_RCON=true -e RCON_PASSWORD=testing -e RCON_PORT 25575
-e MAX_PLAYERS=50
-e ALLOW_NETHER=true
-e ANNOUNCE_PLAYER_ACHIEVEMENTS=true
-e ENABLE_COMMAND_BLOCK=true
-e SPAWN_PROTECTION=0 # disabled
-e VIEW_DISTANCE=10
-e ONLINE_MODE=FALSE
-e SERVER_NAME=MyServer
-e SERVER_PORT=25566
-e NETWORK_COMPRESSION_THRESHOLD -1
-e MOTD="My Server"
-e WHITELIST=user1
-e OPS=user1
#-e SPIGET_RESOURCES=9089,34315 #downloads resources

cd paper-build
docker build . -t test-server
docker rm mc2
docker run -d -it -p 25565:25565 --name mc2 -e EULA=TRUE -e VERSION=1.18.2 test-server:latest

docker exec -i mc2 rcon-cli op reecepbcups
# docker exec mc2 mc-send-to-console op recepbcups

# docker logs --tail 100 mc2
# docker logs --follow mc2

**Comment by reecepbcups** [comment]
### akash commands (instances since closed)

```
akash q deployment list --log_format json --node http://135.181.181.122:28957
akash q deployment get --dseq 5751573 --owner akash1rpv97xasy7px29ccdhy93ar6aj0t8a6895d4n3 --node http://135.181.181.122:28957

akash provider lease-logs --dseq 5751573 --follow --tail 10 --provider akash1r7y2msa9drwjss5umza854he5vwr2czunye9de --from hot-wallet --node http://135.181.181.122:28957
akash provider lease-shell --dseq 5751573 --provider akash1r7y2msa9drwjss5umza854he5vwr2czunye9de --node http://135.181.181.122:28957 --from hot-wallet --tty --stdin -- web /bin/sh

akash provider lease-shell --dseq 5751573 --provider akash1r7y2msa9drwjss5umza854he5vwr2czunye9de --node http://135.181.181.122:28957  --from hot-wallet --tty -- web ls > testls.txt

akash provider lease-shell --dseq 5751573 --provider akash1r7y2msa9drwjss5umza854he5vwr2czunye9de --node http://135.181.181.122:28957  --from hot-wallet --tty -- web rcon-cli
"akash provider lease-shell --dseq {dseq} --provider {provider} --from {WALLET_NAME} --node {RPC_NODE} --tty -- web mc-send-to-console {{COMMAND}}"
```

**Comment by reecepbcups** [comment]
moved to Docs
